title: Janhavi Shankar Tripathi
position: PhD Candidate in Economics
affiliation: Fordham University
email: Email- jtripathi@fordham.edu
CV: http://www.iosrjournals.org/iosr-jef/papers/Vol7-Issue3/Version-2/G0703026070.pdf
keywords: minimal academic
google_scholar: #https://scholar.google.com/
github_link: #https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/in/janhavishankar/
avatar: ./assets/img/jst.png
google_analytics: UA-111540567-4
favicon: ./assets/img/fordham.png
favicon_dark: ./assets/img/fordham.png
description: #The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: #https://minimal-light.yyliu.net/
remote_theme: #yaoyao-liu/minimal-light
