title: Janhavi Shankar Tripathi
position: PhD Candidate in Economics
affiliation: Fordham University
email: jtripathi@fordham.edu
keywords: #minimal academic
google_scholar: #https://scholar.google.com/
github_link: #https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/in/janhavishankar/
researchgate: https://www.researchgate.net/profile/Janhavi-Shankar-Tripathi
orcid: https://orcid.org/0000-0002-7042-1199
ssrn: https://hq.ssrn.com/Participant.cfm?rectype=edit&perinf=y&partid=4266395
avatar: ./assets/img/jst.png
google_analytics: #UA-111540567-4
favicon: ./assets/img/fordham.png
favicon_dark: ./assets/img/fordham.png
description: #The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: #https://minimal-light.yyliu.net/
remote_theme: #yaoyao-liu/minimal-light
